export const GET_FEEDBACK = "GET_FEEDBACK";
export const GET_SPECIFIC_FEEDBACK = "GET_SPECIFIC_FEEDBACK";
export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const DELETE_FEEDBACK = "DELETE_FEEDBACK";

export const GET_FACULTY_FEEDBACK = "GET_FACULTY_FEEDBACK";
export const ADD_FACULTY_FEEDBACK = "ADD_FACULTY_FEEDBACK";
export const UPDATE_FACULTY_FEEDBACK = "UPDATE_FACULTY_FEEDBACK";
