export const GET_VISITINGFACULTY = "GET_VISITINGFACULTY";
export const GET_SPECIFIC_VISITINGFACULTY = "GET_SPECIFIC_VISITINGFACULTY";
export const ADD_VISITINGFACULTY = "ADD_VISITINGFACULTY";
export const UPDATE_VISITINGFACULTY = "UPDATE_VISITINGFACULTY";
export const DELETE_VISITINGFACULTY = "DELETE_VISITINGFACULTY";