export const GET_PROJECT = "GET_PROJECT";
export const GET_SPECIFIC_PROJECT = "GET_SPECIFIC_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";