export const GET_ACHIEVEMENT = "GET_ACHIEVEMENT";
export const GET_SPECIFIC_ACHIEVEMENT = "GET_SPECIFIC_ACHIEVEMENT";
export const ADD_ACHIEVEMENT = "ADD_ACHIEVEMENT";
export const UPDATE_ACHIEVEMENT = "UPDATE_ACHIEVEMENT";
export const DELETE_ACHIEVEMENT = "DELETE_ACHIEVEMENT";