export const GET_FACULTY = "GET_FACULTY";
export const GET_SPECIFIC_FACULTY = "GET_SPECIFIC_FACULTY";
export const ADD_FACULTY = "ADD_FACULTY";
export const UPDATE_FACULTY = "UPDATE_FACULTY";
export const DELETE_FACULTY = "DELETE_FACULTY";