export const GET_BROCHURE = "GET_BROCHURE";
export const GET_SPECIFIC_BROCHURE = "GET_SPECIFIC_BROCHURE";
export const ADD_BROCHURE = "ADD_BROCHURE";
export const UPDATE_BROCHURE = "UPDATE_BROCHURE";
export const DELETE_BROCHURE = "DELETE_BROCHURE";